<?php
/** @var \Radarsofthouse\BillwerkPlusSubscription\Block\Paymenticons $block */
$paymentIcons = $block->getPaymentIcons();
?>
<?php if (count($paymentIcons) > 0): ?>
    <?php foreach ($paymentIcons as $paymentIcon): ?>
        <?php
        $fieldUrl = 'Radarsofthouse_BillwerkPlusSubscription::img/payment_icons/'.$paymentIcon.'.png';
        $imageUrl = $block->getViewFileUrl($fieldUrl);
        ?>
        <img class="billwerkplus-payment-icon"
             src="<?= $escaper->escapeUrl($imageUrl); ?>" alt="<?= $escaper->escapeUrl($paymentIcon) ?>">
    <?php endforeach; ?>
<?php endif; ?>



