<?php
/** @var \Radarsofthouse\BillwerkPlusSubscription\Block\Customer\Subscriptions $block */
$subscriptions = $block->getSubscriptions();

if (empty($subscriptions)): ?>
    <div class="message info empty">
        <span><?= $escaper->escapeHtml(__("You do not have any active subscriptions.")); ?></span>
    </div>
<?php else: ?>
    <div class="table-wrapper stripe-subscriptions">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__("Subscriptions")); ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col subscription-id"><?= $escaper->escapeHtml(__("Subscription ID")); ?></th>
                <th scope="col" class="col status"><?= $escaper->escapeHtml(__("Plan")); ?></th>
                <th scope="col" class="col status"><?= $escaper->escapeHtml(__("Status")); ?></th>
                <th scope="col" class="col next-payment"><?= $escaper->escapeHtml(__("Next Payment")); ?></th>
                <th scope="col" class="col amount"><?= $escaper->escapeHtml(__("Amount")); ?></th>
                <th scope="col" class="col action"><?= $escaper->escapeHtml(__("Actions")); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($subscriptions as $subscription):
                $addons = $block->getSubscriptionAddOns($subscription);
                $totalAddonsAmount = $block->getTotalAddonsAmount($addons);
                $planAmount = $block->getPlanPrice($subscription['plan']);
                $subscriptionAmount = $planAmount['price'] + $totalAddonsAmount['amount'];
                if ($subscriptionAmount > 0) {
                    $subscriptionAmount = "$subscriptionAmount ". ($planAmount['currency'] ?? $totalAddonsAmount['currency']);
                }
                $addonsName = $block->getAddonsName($addons);
                ?>
                <tr class="<?= $escaper->escapeHtml($subscription['handle']); ?>">
                    <td data-th="<?= $escaper->escapeHtml(__("Subscription ID")) ?>" class="col subscription-id">
                        <a href="<?= $escaper->escapeUrl($block->getUrl(
                            'billwerkplussubscription/customer/subscriptionview',
                            ['handle' => $subscription['handle']]
                        )) ?>">
                            <?= $escaper->escapeHtml($subscription['handle']); ?>
                        </a>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__("Name")); ?>" class="col status">
                        <div class="subscription-status">
                            <?= $escaper->escapeHtml($block->getPlanName($subscription['plan']) . $addonsName); ?>
                        </div>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__("Status")); ?>" class="col status">
                        <div class="subscription-status">
                            <?= $escaper->escapeHtml(__($subscription['is_cancelled'] ?
                                'Cancel' : ucfirst(str_replace('_', ' ', $subscription['state'])))); ?>
                            <?php if ($subscription['in_trial']): ?>
                                <span class="billwerkplus-subscription-trial">
                                / <?= $escaper->escapeHtml(__('Trial period')); ?>
                            </span>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__("Next Payment")); ?>" class="col next-payment">
                        <div class="subscription-next-payment">
                            <?= $escaper->escapeHtml($block->dateFormat($subscription['next_period_start'])); ?>
                        </div>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__("Amount")); ?>" class="col amount">
                        <div class="subscription-amount">
                            <?= $escaper->escapeHtml($subscriptionAmount); ?>
                        </div>
                    </td>
                    <td data-th="Actions" class="col">
                        <a href="<?= $escaper->escapeUrl($block->getUrl(
                            'billwerkplussubscription/customer/subscriptionview',
                            ['handle' => $subscription['handle']]
                        )); ?>" class="action view">
                            <span>View</span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
