<?php
/* @var $block \Radarsofthouse\BillwerkPlusSubscription\Block\Adminhtml\Customer\Edit\Tab\View\Subscription */
$handle = $block->getSubscriberHandle();
$subscriptions = $block->getSubscriptions();
$adminBillPlusLink = "https://admin.billwerk.plus/#/rp/";
?>
<?php if ($handle):
    $customerLink = $adminBillPlusLink."customers/customers/customer/".$handle; ?>
<div class="fieldset-wrapper-title">
    <span class="title"><?= $escaper->escapeHtml(__('Subscriber handle')) ?>:
        <a target="_blank" href="<?= $escaper->escapeHtml($customerLink) ?>"><?= $escaper->escapeHtml($handle); ?></a>
    </span>
</div>
<div id="view_subscription_grid" data-grid-id="view_subscription_grid">
    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <table class="data-grid" id="view_subscription_grid_table">
            <thead>
            <tr>
                <th class="data-grid-th  no-link col-handle"><span><?= $escaper->escapeHtml(__('Subscription handle')) ?></span></th>
                <th class="data-grid-th  no-link col-plan"><span><?= $escaper->escapeHtml(__('Plan handle')) ?></span></th>
                <th class="data-grid-th  no-link col-state"><span><?= $escaper->escapeHtml(__('Subscription status')) ?></span></th>
            </tr>
            </thead>
            <tbody>
            <?php
            if ($subscriptions):
                foreach ($subscriptions as $subscription):
                    $handleLink = $adminBillPlusLink."subscriptions/subscription/".$subscription['handle'];
                    $planLink = $adminBillPlusLink."config/plans/edit/".$subscription['plan'];
                    ?>
                    <tr title="">
                        <td class="col-handle">
                            <a target="_blank" href="<?= $escaper->escapeHtml($handleLink) ?>">
                                <?= $escaper->escapeHtml($subscription['handle']) ?>
                            </a>
                        </td>
                        <td class="col-plan">
                            <a target="_blank" href="<?= $escaper->escapeHtml($planLink) ?>">
                                <?= $escaper->escapeHtml($subscription['plan']) ?>
                            </a>
                        </td>
                        <td class="col-state">
                            <?= $escaper->escapeHtml($subscription['is_cancelled'] ? 'Cancel' :
                                ucfirst(str_replace('_', ' ', $subscription['state']))); ?>
                        </td>
                    </tr>
                <?php endforeach;
            else:
                ?>
                <tr class="data-grid-tr-no-data even">
                    <td class="empty-text" colspan="11"><?= $escaper->escapeHtml(__('We couldn\'t find any records.')) ?></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
<?php endif; ?>
