<?php
/* @var $block \Radarsofthouse\BillwerkPlusSubscription\Block\Adminhtml\System\Config\Webhook */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){
        var subscriptionWebhookSpan = jQuery('#subscription_webhook_span');
        jQuery('#subscription_webhook_button').click(function () {
            var params = {};
            new Ajax.Request('<?= $escaper->escapeUrl($block->getAjaxUrl()) ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    subscriptionWebhookSpan.find('.updated').hide();
                    subscriptionWebhookSpan.find('.processing').show();
                    jQuery('#webhook_message_span').text('');
                },
                onSuccess: function(response) {
                    subscriptionWebhookSpan.find('.processing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        let jsonResponse = response.responseJSON;
                        if(jsonResponse.success === true){
                            // resultText = 'Updated at:'+jsonResponse.time;
                            resultText = 'Updated.';
                            subscriptionWebhookSpan.find('.updated').show();
                        }else{
                            resultText = 'Something went wrong!';
                            subscriptionWebhookSpan.find('.processing').hide();
                        }
                    }
                    jQuery('#webhook_message_span').text(resultText);
                }
            });
        });

    });
</script>

<?= $block->getButtonHtml() ?>
<span class="collect-indicator" id="subscription_webhook_span">
    <img class="processing" hidden="hidden" alt="Processing" style="margin:0 5px"
        src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')) ?>"/>
    <img class="updated" hidden="hidden" alt="Updated" style="margin:-3px 5px"
        src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/rule_component_apply.gif')) ?>"/>
    <span id="webhook_message_span"></span>
</span>
